PR
MVetukh/Perceptron pull request #1
Opened 2023-10-28 14:10 UTC by MVetukh

2023-10-29 18:53 UTC, FedorenkoKirill requested changes

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +# -*- coding: utf-8 -*-
Первое, что бросается больше всего в глаза - код стайл. Обязательно почитай PEP 8, там в целом не много и всё довольно просто. Это сделает твой код значительно читабельнее и проще. Можно пользоваться всякими инструментами для проверки код стайла, но и сам PyCharm очень хорошо подсказывает тебе, что ты делаешь не так. Постарайся избавиться от всех волнистых подчёркиваний в PyСharm.

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +
Сюда принято вставлять следующую конструкцию:
`if __name__ == __main__:`
И потом весь исполняемый код писать внутри этого условия. Это потом позволит избежать очень неприятных последствий. Допустим, если соберешься импортировать свой класс в другом файле, то код который ниже выполнится, а условие, которое я написал чуть выше спасёт тебя от такого выстрела в ногу. Да и в целом это best practices

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +class Network(object):
Если честно я такое наследование вижу впервые. Бегло посмотрел что это такое. Как я понял наследование от `object` было актуально во 2-ой версии языка. Сейчас пользовательские классы и так наследуются от `object` и необходимости в явном наследовании нет. Более корректно будет:
 `class Network:`

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +        dw,db = self.backprop(x[i][0],t[i][0])
Тут, если я правильно понял, ты пытаешься учить модель. Говоришь, что кол-во эпох у тебя такое-же как и кол-во данных и потом каждую эпоху скармливаешь по одной точке на графике. Это немного не так должно работать. За одну эпоху ты должен скармливать весь тренировочный датастет, после каждой фотки (или пакета фоток) считать лосс и корректировать веса, далее ты перемешиваешь тренировочный датасет и скармливаешь его ещё раз и так N раз. Кол-во эпох - гиперпараметр, который, грубо говоря подбирается на глаз.

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +  def train(self,x,true):
Ещё придирка по поводу namespace-а. В целом с тем ка ты обозвал первый аргумент я согласен, но давай лучше сделаем `data` или `argument` (как аргумент функции). Со вторым плохая история использовать пространство имён языка для обзывания переменных (да, true и True разные вещи, но всё же). Можно обозвать второй как `value` (значение функции). На самом деле в разных областях ml этот нейминг разный в зависимости от контекста, поэтому привыкать надо каждый раз к новому

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +    delta_w = [np.zeros(w.shape) for w in self.weights]
Не сокращай, пожалуйста, слова в названиях переменных до букв. Не стесняйся написать название переменной на пол строки. Главное, чтобы его можно было легко прочесть, человеку из вне или просто тебе вспомнить через месяц

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +  def feedforward(self, a):
`forward` будет правильнее

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +     for b, w in zip(self.biases, self.weights):
Не сокращай до букв. Пусть будет `bias` и `weight`

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +def f(x):
На первый взгляд не понятно что это тангенсальная функция активации, обзови её лучше `tanh`. И такая функция активации избыточна для тебя, тк ты аппроксимируешь линейную функцию, то и лучше использовать линейную функцию активации, так ты минимизируешь места, в которых можешь ошибиться.

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +        a = f(np.dot(w, a)+b)
У тебя какая-то лажа со смещениями. Из-за них твои предсказания вылетают в 1. Для аппроксимации линейной функции они тебе не нужны пока убери, а как получится обучить модельку, вернёшь и найдёшь где косякнул

2023-10-29 18:53 UTC, FedorenkoKirill commented on Percep.py
> +def f(x):
Если убрать нейроны смещения, то тангенсальная функция активации начинает сильно гнуть твои предсказания 
![image](https://github.com/MVetukh/Perceptron/assets/62508710/11decdf5-cfa0-4e49-b7d9-18737896d4b1)
![image](https://github.com/MVetukh/Perceptron/assets/62508710/5f4c57ab-e14e-44b9-b12f-7358d93af078)

2023-10-31 16:01 UTC, MVetukh commented on Percep.py
> +# -*- coding: utf-8 -*-
Код стайл поправил, теперь надеюсь он стал более читабельным. Хотя проблемы с обучением остались

2023-10-31 16:01 UTC, MVetukh commented on Percep.py
> +    return data #1/(1+np.exp(-data))
Я поменял функция активации на линейную, но теперь предсказания выглядит рандомными. Изменение гиперпараметров типа эпох или скорости обучения, количества слоев и т.д. влияют лишь на диапазон разброса

2023-11-03 21:24 UTC, MVetukh commented on Percep.py
> +# -*- coding: utf-8 -*-
Сеть выдает предсказания рандомно, а изменение гиперпараметров(типо эпох, количество нейронов в скрытом слое, скорость обучения) изменяют лишь диапазон разброса. Но ошибки в коде я пока не нашел, по размерностям все совпадает.

2023-11-08 20:01 UTC, MVetukh commented on Percep.py
> +    net = Network([100, 10,15, 100])
Полагаю ошибка не в реализации алгоритме, а в выборе архитектуры(кол-во слоев, нейронов). Как они вообще выбираются, нет ли какой-то методики подбора или типо того. Из того, что я нагуглил ощущение, что все это подбирается "на глаз" или то, что уже было подобрано методом проб и ошибок.

2023-11-11 09:12 UTC, MVetukh commented on Percep.py
> +        self.weights = [weight - self.learning_rate * delta for weight, delta in
Когда я делал сеть размером [100,n,100], те сеть принимала все точки сразу, на выходе она выдавала просто случайно разбросанные предсказания, но она имеет вид [1, n ,1] она хотя бы понимает, что нужно рисовать прямую, и при разных запусках предсказания неплохо совпадают. Но это все еще неверно.

2023-11-13 06:35 UTC, FedorenkoKirill commented on Percep.py
> +    net = Network([100, 10,15, 100])
Вообще в случае с написанием больших сеток, то да, ты выбираешь на глаз, т.е. читаешь статьи, смотришь какие архитектуры там и пытаешься сделать что-то подобное. Но в нашем с тобой случае, тк мы аппроксимируем мат функцию, то мы можем рассчитать количество слоёв, которое нам надо. В случае с линейной функцией тебе достаточно одного нейрона с линейной функцией активации.

2023-11-15 19:49 UTC, MVetukh commented on Percep.py
> +# class Network:
Изначально, я хотел написать кастомный класс перцептрона, т.е. такой, что можно было бы изменять количество слоев, нейронов, эпох, не залезая в сам класс, но он почему то не работает, хотя размерности и алгоритм вроде верной, скорее всего проблема на этапе тренировки, но нормально исправить у меня так и не получилось. Вечно стоять на месте, пытаясь саппроксимировать мат функции мне не хочется, поэтому я решил переписать все ''по тупому''  и просто прописать все руками, это менее прикольно, но тем не менее, надеюсь на поздних этапах я все-таки сделаю его таким каким задумывал.

2023-11-15 19:49 UTC, MVetukh commented on Percep.py
> +class MLP:
Здесь возникает проблема, которая у меня была с самого начала, проблема с сигмоидой, точнее с экспонентой, 
оно выдает ошибку RuntimeWarning: overflow encountered in exp, в интернете пишут, что это предупреждение и его можно игнорить, но из-за этого все предикты заганяются в ноль, как я понимаю это из-за больших значений аргументов

2023-11-18 12:56 UTC, FedorenkoKirill requested changes

2023-11-18 12:56 UTC, FedorenkoKirill commented on .gitignore
> +.idea/**/workspace.xml
Смотри, да ты составил gitignore с помощью того сайтика, но у тебя всё равно папка .idea попала в гит из-за чего все у кого PyCharm при попытке склонить твою репу словят пачку конфликтов. Добавь сюда строчку `.idea`, спушь, удали эту папку в самом гите и спуль изменения

2023-11-18 12:56 UTC, FedorenkoKirill commented on Percep.py
> +
Совсем забыл, в ml принято пользоваться генератором псевдослучайных чисел. Делается это для того, чтобы от запуска к запуску у тебя веса, которые ты задаёшь рандомно не менялись. Если ты пропишешь генератор, то у видишь, что рандом в предсказаниях уйдёт, т.е. у тебя будет каждый раз один и тот же график. Делается это в одну строку `np.random.seed(0)`, где вместо 0 любое целое число

2023-11-18 12:56 UTC, FedorenkoKirill commented on Percep.py
> +        return self.weights * argument + self.bias
тут логика правильная, но ты забыл или специально опустил функцию активации. В этом случае функция активация - линейная, из-за чего ничего не измениться, поэтому её можно опускать, но лучше давай её оставим, для лучшего понимания

2023-11-18 12:56 UTC, FedorenkoKirill commented on Percep.py
> +        self.Weight_1 = np.random.randn(1, 10)  # Веса первого слоя
переменные и поля классов нужно обзывать с маленькой буквы, только названия классов нужно называть с большой буквы
и когда ты пишешь класс сети, то в полях у тебя не веса, а слои. Вес - общее поле всей сети
правильнее будет обозвать `self.layer_1`

2023-11-18 12:56 UTC, FedorenkoKirill commented on Percep.py
> +        self.a2 = ReLu(self.z2)
а вот один из главных косяков, по сути ReLu - та же самая линейная функция активации, только обрезаная, а ты хочешь аппроксимировать параболическую функцию, т.е. тебе нужна какая-то изогнутая функция активации, тут лучше поиграться с сигмоидой 
и почитай [вот эту статейку](https://habr.com/ru/articles/727506/)

2023-11-18 12:56 UTC, FedorenkoKirill commented on Percep.py
> +# class Network:
Вся сложность закрыта в backprop, там надо считать производную по всей сети, и делать кастомный класс руками штука крайне сложная, с такой задачей не каждый сеньёр справиться. Вообще у меня изначально была задумка делать эту задачу на torch, но ты с таким энтузиазмом побежал делать всё руками, что я не стал тебя останавливать. Но если сравнить текущий коммит с первыми, то ты достиг значительного прогресса, делай пункты, что я описал в ВК и можно сворачиваться с этой задачей

2023-11-18 12:56 UTC, FedorenkoKirill commented on Percep.py
> +def line(data):
давай немного отрефакторим этот проект
1) все мат функции вынесем в отдельный файл
2) в отдельный файл вынесем каждую сетку (получится 3 файла)
3) сделаем отдельный файл для обучения

2023-11-23 15:55 UTC, MVetukh commented on custom_class
> +# class Network:
Ну я все еще не потерял надежд написать свой кастомный класс. Я прочитал, что зачастую входные данный принято разделять на мини батчи. Это улучшает обучение.(Но это потом как-нибудь)

2023-11-23 15:55 UTC, MVetukh commented on quad_approximation.py
> +    def backpropogation(self, argument, value, learning_rate= 0.001):
Честно, я не знаю почему не выходит, учитывая, что я полностью взял backprop из статьи. Вылетает ошибка, которая тянется еще с тех попыток, когда я пытался написать кастомный класс: RuntimeWarning: overflow encountered in exp return 1 / (1 + np.exp(-data)). Как я понял это связано со значениями экспоненты, типо из-за больших значений аргумента функция залетает в ноль. И без понятия как это обойти.

2023-11-24 17:54 UTC, FedorenkoKirill commented on custom_class
> +# class Network:
Разделение на батчи нужно по сути, для ускорения процесса обучение, тк ты отправляешь на видеокарту не одну картинку, а несколько. И гонишь параллельно через back и forward flow

2023-11-24 21:59 UTC, FedorenkoKirill requested changes

2023-11-24 21:59 UTC, FedorenkoKirill commented on __pycache__/math_func.cpython-39.pyc
нет-нет, но что-то не то у тебя в гит попадает периодически. Следи внимательно за тем, что ты пушишь

2023-11-24 21:59 UTC, FedorenkoKirill commented on Percep.py
>  if __name__ == '__main__':
С код стайлом стало **значительно** лучше, но вот так писать не принято. Считается дурным тоном. Лучше создай функцию main и запихай всё в неё а саму функцию вызови тут

2023-11-24 21:59 UTC, FedorenkoKirill commented on Percep.py
> +    Quad_Aproximate = quad_approximation.Quadratic_Approximation(1,1,1)
1) объект класса принято писать с маленькой буквы
2) так импортировать классы тоже не принято. Правильнее будет так:
```
from quad_approximation import Quadratic_Approximation
...
quad_aproximate = Quadratic_Approximation(1,1,1)
```

2023-11-24 21:59 UTC, FedorenkoKirill commented on .gitignore
> +.idea/**/workspace.xml
Не забывай закрывать мои комменты, после того как всё исправил, а то прям свалка получается

2023-11-24 21:59 UTC, FedorenkoKirill commented on math_func.py
> +def ReLu(x):
Даже несмотря на то, что сама мат функция называется ReLu, функцию надо называть relu. В большинстве фреймворков она называется с большой буквы, потому что это у них класс

2023-11-24 21:59 UTC, FedorenkoKirill commented on percep_torch.py
> +data = np.arange(-10, 10, 1)
тоже не оч хорошая история, лучше вынеси в if __name__ ...

2023-11-24 21:59 UTC, FedorenkoKirill commented on quad_approximation.py
> +    def backpropogation(self, argument, value, learning_rate= 0.001):
` D = math_func.dsigmoid(E)`
смотри, когда ты считаешь F, E, D, C, B - это forward propagation, т.е. просто проход по сетке со слоям, по сути это твой predict. И тут должна сидеть обычная сигмоида, а не производная от неё

Если убрать из вычислений веса смещений и убрать их в принципе из сетки, то ситуация не измениться вообще, твои предсказания и лоссы летят в бесконечность
причём веса первого слоя летят в минус бесконечность, второго летят в бесконечность
почему это происходит - хрен его знает, надо разбираться в математики
и честно говоря, чем мы сильнее закапываемся в аппроксимацию квадратичной функции, тем мы дальше уходим от коммерческого ml в сторону академического, а он нам на текущем этапе не нужен, да и в академическом ml я 0, если честно
поэтому давай пока завязывать с этой штукой, сильно мы на ней засиделись

2023-11-24 21:59 UTC, FedorenkoKirill commented on percep_torch.py
> +        self.fc1 = nn.Linear(1, 10)
Смотри, ты пользуешься линейными слоями, а именно ты пытаешься аппроксимировать квадратичную функцию линейной, поэтому график твоих предсказаний - ломанная линия. И чем больше ты указываешь скрытых слоёв, тем более качественная аппроксимация, но при этом это та же самая ломанная линия. Но если сюда воткнуть ту же сигмоиду, то аппроксимация будет более гладкой

2023-11-25 11:25 UTC, closed without merging